from google import genai

client = genai.Client()

response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents="Explain Natural-Language-to-SQL in one sentence."
)

print(response.text)



import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="stylekart_capstone"
)

cursor = db.cursor()

print("MySQL connection successful!")
cursor.execute("SHOW TABLES;")

for table in cursor.fetchall():
    print(table)



schema = """
Database: stylekart_capstone

Tables:

Customers:
Customer_ID, Customer_Name, Age, Gender, City, State,
Region, Customer_Segment, Registration_Date

Products:
Product_ID, Product_Name, Category, Brand, Price

Orders:
Order_ID, Customer_ID, Product_ID, Order_Date,
Quantity, Order_Amount, Order_Status

Payments:
Payment_ID, Order_ID, Payment_Method,
Payment_Status, Amount

Returns:
Return_ID, Order_ID, Product_ID, Return_Reason,
Return_Quantity, Refund_Amount

Inventory:
Inventory_ID, Last_Updated, Product_ID,
Reorder_Level, Stock_Quantity, Warehouse
"""


question = """
Which product categories generated the highest revenue?
"""


prompt = f"""
You are a SQL analyst working with the StyleKart
fashion e-commerce database.

Database schema:
{schema}

Business question:
{question}

Generate a MySQL query that answers the business question.

Rules:
- Use only the tables and columns provided in the schema.
- Do not invent columns.
- Use correct JOIN conditions.
- Use appropriate aggregation.
- Sort the result when ranking is requested.
- Return only the SQL query.
"""


response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt
)

generated_sql = response.text.strip()

print("\nGenerated SQL:")
print(generated_sql)


generated_sql = generated_sql.replace("```sql", "")
generated_sql = generated_sql.replace("```", "")
generated_sql = generated_sql.strip()
print("\nSQL generated by Gemini:")
print(generated_sql)



cursor.execute(generated_sql)

rows = cursor.fetchall()

print("\nQuery Result:")
for row in rows:
    print(row)





# PART 19 — AI-ASSISTED INSIGHTS

# Store the verified MySQL result
verified_result = "\n".join(
    [f"{row[0]}: {row[1]}" for row in rows]
)

print("\nVerified Result:")
print(verified_result)


# Create the insight prompt
insight_prompt = f"""
You are helping prepare a business insights report
for StyleKart Fashion E-Commerce & Retail.

Below is a verified analytical result.

{verified_result}

Convert this result into a concise business insight.

Rules:
- Do not invent numbers.
- Do not change any values.
- State the observed pattern objectively.
- Clearly distinguish facts from possible interpretations.
- Do not claim causation unless supported by the data.
- Explain why the finding may matter to StyleKart.
"""


# Send the verified result to Gemini
insight_response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=insight_prompt
)

print("\nAI-Assisted Business Insight:")
print(insight_response.text)